In [3]:
# 정수형 series 
import pandas as pd
s= pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [6]:
# 실수형 series
s = pd.Series([1.3,2.5,3.6,2.3,1.2])
print(s)

0    1.3
1    2.5
2    3.6
3    2.3
4    1.2
dtype: float64


In [8]:
# 인덱스 지정
s = pd.Series([1.3,2.5,3.6,2.3,1.2], index=['a','b','c','d','e'])
print(s)

a    1.3
b    2.5
c    3.6
d    2.3
e    1.2
dtype: float64


In [14]:
import numpy as np
a = np.array([1,2,3])
print(a)

b = np.zeros(5)
print(b)

c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:

a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
# 요소별 합
print(np.add(a,b))
# 요소별 곱
print(np.multiply(a,b))
# 요소별 평균
print(np.mean(a))

[5 5 5 5]
[4 6 6 4]
2.5
