In [3]:
# 정수형 series 
import pandas as pd
s= pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [6]:
# 실수형 series
s = pd.Series([1.3,2.5,3.6,2.3,1.2])
print(s)

0    1.3
1    2.5
2    3.6
3    2.3
4    1.2
dtype: float64


In [8]:
# 인덱스 지정
s = pd.Series([1.3,2.5,3.6,2.3,1.2], index=['a','b','c','d','e'])
print(s)

a    1.3
b    2.5
c    3.6
d    2.3
e    1.2
dtype: float64


In [14]:
import numpy as np
a = np.array([1,2,3])
print(a)

b = np.zeros(5)
print(b)

c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:

a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
# 요소별 합
print(np.add(a,b))
# 요소별 곱
print(np.multiply(a,b))
# 요소별 평균
print(np.mean(a))

[5 5 5 5]
[4 6 6 4]
2.5


In [24]:
# 0 과 1 사이에서 균일한 분포를 갖는 숫자 샘플링
a = np.random.rand(2,5)
print(a)

# 표준정규분포를 갖는 숫자들 샘플링
b = np.random.rand(2,4)
print(b)

[[0.24063579 0.16614696 0.10917487 0.00344463 0.88174884]
 [0.13377907 0.67741998 0.49402205 0.81319071 0.73201419]]
[[0.54886999 0.91191647 0.36900111 0.14612635]
 [0.14179585 0.96668697 0.32055479 0.78703204]]


In [26]:
# 파이
a = np.pi
print(a)
# 오일러 상수
b = np.e
print(b)

3.141592653589793
2.718281828459045


In [28]:
a = np.array([1,2,5,6,8])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[1 2 5 6 8]
int32


In [39]:
a = np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [42]:
# 타입 지정
a = np.array([[1,2,3],[4,5,6]],dtype=complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [49]:
a = np.zeros(10)
print(a)
print(np.ones((2,3,4), dtype = np.int16))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [50]:
no = [1,2,3]
sn = []
sn.append('수학')
sn.append('과학')
sn.append('파이썬')

In [55]:
su = pd.DataFrame()
su['과목번호'] = no
su['과목명'] = sn
print(su)
su.to_excel("C:\\Users\\Administrator\\Desktop\\py2\\day05\\subject.xlsx", index=False)

   과목번호  과목명
0     1   수학
1     2   과학
2     3  파이썬


In [56]:
su.to_csv("C:\\Users\\Administrator\\Desktop\\py2\\day05\\subject.csv", encoding='utf-8-sig',index=False)